### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by XIEBELL** [nota-github/AIC2023_Track1_Nota#1]
helloHello, I am very happy to see your performance in the 2023ai city challenge. You are so awesome. Could you please help share the data set? I cannot access the official website of 2023ai city challenge, thank you

**Comment by qkqk772** [comment]
Hello, I apologize but I am unable to deploy dataset due to the DATASET LICENSE AGREEMENT.
I hope you can receive the dataset directly from AI City.
