### ISSUE TITLE
Online Camera Stream & Visualization Code

### ISSUE THREAD

**Issue by VoXuanThuy** [nota-github/AIC2023_Track1_Nota#3]
Thank you for your great work. I have two concerns about your methods:
1. Is your method online?
2. Could you share the code to visualize the multi-cameras results?
Thank you so much!

**Comment by wooksu** [comment]
hello. Firstly, I would like to apologise for the delay in responding.
1. online is correct.
2. when you run eval_*.py, the output video(visualized) is also saved.
