### ISSUE TITLE
Where is the map data?

### ISSUE THREAD

**Issue by maligawork** [nota-github/AIC2023_Track1_Nota#4]
Hi, thanks for your work. I have accessed the AI CITY CHALLENGE 2024 data, but I don't see any "map.png", the calibration is represented by camera matrices and homography.  Can you please explain how to get "map.png". Do I understand correctly that "map_position" and "cam_position" are just points to calculate the homography matrix between the screen and the map?

**Comment by qkqk772** [comment]
Sorry for late reply.
The "map.png" was provided only in the 2023 data. And as you said, "map_position" and "cam_position" were used to calculate the homography matrix. It seems that the 2024 data did not provide the "map.png" because it provided all the homography matrix values.
